In [1]:
import math

def plogp(p):
    if p < 1e-5:
        return 0
    else:
        return round(p * math.log2(p), 3)

def H(p1, p2):
    total = p1 + p2
    entropy = -(plogp(p1 / total) + plogp(p2 / total))
    return round(entropy, 3)

def avg(items, ps=None):
    if ps is None:
        return sum(items) / len(items)
    return round(sum(item * p for item, p in zip(items, ps)) / sum(ps), 3)

色泽：

In [2]:
H(8, 9), H(3, 3), H(4, 2), H(1, 4)

(0.998, 1.0, 0.918, 0.722)

In [3]:
IG = H(8, 9) - avg((H(3, 3), H(4, 2), H(1, 4)), (6, 6, 5))
print("%.3f" % IG)

0.109


batch process:

In [15]:
import numpy as np
import math

def plogp(p):
    if p < 1e-5:
        return 0
    else:
        return round(p * math.log2(p), 3)

def H(p1, p2):
    total = p1 + p2
    if total < 1e-5:
        return 0
    entropy = -(plogp(p1 / total) + plogp(p2 / total))
    return round(entropy, 3)

def avg(items, ps=None):
    if ps is None:
        return sum(items) / len(items)
    return round(sum(item * p for item, p in zip(items, ps)) / sum(ps), 3)


# 色泽 青绿：0 乌黑：1 浅白：2
# 根蒂 蜷缩：0 稍蜷：1 硬挺：2
# 敲声 浊响：0 沉闷：1 清脆：2
# 纹理 清晰：0 稍糊：1 模糊：2
# 脐部 凹陷：0 稍凹：1 平坦：2
# 触感 硬滑：0 软粘：1 

features = 6

def sim(D_p, D_n, feature):
    count_p = np.array([])
    count_n = np.array([])
    for v in np.arange(3):
        
        cnt_set = np.array([])
        for idx in np.arange(len(D_p)):
            if D_p[idx][feature] == v:
              
                cnt_set = np.append(cnt_set, idx)
        print(cnt_set)
        count_p = np.append(count_p,len(cnt_set))
    for v in np.arange(3):
       
        cnt_set = np.array([])
        for idx in np.arange(len(D_n)):
            if D_n[idx][feature] == v:
                
                cnt_set = np.append(cnt_set, idx)
        print(cnt_set)
        count_n = np.append(count_n,len(cnt_set))
    
    print(H(sum(count_p), sum(count_n)), H(count_p[0], count_n[0]), H(count_p[1], count_n[1]), H(count_p[2], count_n[2]))
    IG = H(sum(count_p), sum(count_n))-avg((H(count_p[0], count_n[0]), H(count_p[1], count_n[1]), H(count_p[2], count_n[2])),
                                           (count_p[0]+count_n[0],count_p[1]+count_n[1],count_p[2]+ count_n[2]))
    print("%.3f" % IG)

# dataset
D_0_0_p =np.array([
    [0,0,0,0,0,0],
    [1,0,1,0,0,0],
    [1,0,0,0,0,0],
    [0,0,1,0,0,0],
    [2,0,0,0,0,0],
    [0,1,0,0,1,1],
    [1,1,0,1,1,1],
    [1,1,0,0,1,0]
])
D_0_0_n = np.array([
    [1,1,1,1,1,0],
    [0,2,2,0,2,1],
    [2,2,2,2,2,0],
    [2,0,0,2,2,1],
    [0,1,0,1,0,0],
    [2,1,1,1,0,0],
    [1,1,0,0,1,1],
    [2,0,0,2,2,0],
    [0,0,1,1,1,0]
])

# for feature in np.arange(features):
#     print("feature = "+str(feature)+":")
#     sim(D_0_0_p,D_0_0_n,feature)
# sim(D_0_0_p,D_0_0_n,4)
D_1_0_p = np.array([])
for idx in [0, 1, 2, 3, 4, 5, 7]:
    D_1_0_p = np.append(D_1_0_p, D_0_0_p[idx])
D_1_0_p =  D_1_0_p.reshape(7,6)
D_1_1_p = [D_0_0_p[6]]

# [6.]
# []

D_1_0_n = np.array([])
for idx in [1,6]:
    D_1_0_n = np.append(D_1_0_n, D_0_0_n[idx])
D_1_0_n = D_1_0_n.reshape(2,6)
# [1. 6.]
D_1_1_n = np.array([])
for idx in [0,4,5,8]:
    D_1_1_n = np.append(D_1_1_n, D_0_0_n[idx])
D_1_1_n = D_1_1_n.reshape(4,6)
# [0. 4. 5. 8.]
# [2. 3. 7.]

# for feature in np.arange(features):
#     print("feature = "+str(feature)+":")
#     sim(D_1_0_p,D_1_0_n,feature)

# [0. 1. 2. 3. 4.]
# [5. 6.]
# []
# []
# [1.]
# [0.]
D_2_0_p = np.array([])
for idx in [5,6]:
    D_2_0_p = np.append(D_2_0_p, D_1_0_p[idx])
D_2_0_p =  D_2_0_p.reshape(2,6)
D_2_0_n = [D_1_0_n[1]]

for feature in np.arange(features):
    print("feature = "+str(feature)+":")
    sim(D_2_0_p,D_2_0_n,feature)

feature = 0:
[0.]
[1.]
[]
[]
[0.]
[]
0.918 -0.0 1.0 0
0.251
feature = 1:
[]
[0. 1.]
[]
[]
[0.]
[]
0.918 0 0.918 0
0.000
feature = 2:
[0. 1.]
[]
[]
[0.]
[]
[]
0.918 0.918 0 0
0.000
feature = 3:
[0. 1.]
[]
[]
[0.]
[]
[]
0.918 0.918 0 0
0.000
feature = 4:
[]
[0. 1.]
[]
[]
[0.]
[]
0.918 0 0.918 0
0.000
feature = 5:
[1.]
[0.]
[]
[]
[0.]
[]
0.918 -0.0 1.0 0
0.251
